### ISSUE TITLE
Cannot find module 'jsrsasign' in scripts since v3.0.0 Afficher plus de lignes

### ISSUE THREAD

**Issue by TestSoar** [usebruno/bruno#9017]
### I have checked the following:

- [x] I have searched existing issues and found nothing related to my issue.

### This bug is:

- [ ] Making Bruno unusable for me.
- [ ] Slowing me down but I'm able to continue working.
- [ ] Annoying.
- [x] This feature was working in a previous version but is broken in the current release.

### Bruno version

4.0.0

### 💻 Operating System

Windows

### 🐞 Describe the bug

Bruno version:
- Works in 2.0.0
- Fails in 3.0.0
- Fails in 4.0.0

Script:

const KJUR = require('jsrsasign');

Error:

Cannot find module 'jsrsasign'

Context:
We use jsrsasign in a pre-request script to generate a JWT client_assertion for an Okta private_key_jwt flow.

The same collection works without modification in Bruno 2.0.0.
``

### 📝 Steps to reproduce

- Has an API with a script using jsrsasign.
- Launch it on 2.0.0 version (it's working)
- Launch it again after install 4.0.0 version (it's not working anymore)

### 📷 Screenshots/Live demo link

I have not rights to share it

**Comment by Rohan-Bruno** [comment]
Hi @TestSoar, thanks for reporting this!

Have you tried using "[Developer Mode](https://docs.usebruno.com/get-started/configure/javascript-sandbox#javascript-sandbox)" with this you can use external npm packages in your scripts.

Let us know how this goes.
