### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toLocaleString')

### ISSUE THREAD

**Issue by Bradleykingz** [usebruno/bruno#4573]
### I have checked the following:

- [x] I have searched existing issues and found nothing related to my issue.

### This bug is:

- [x] making Bruno unusable for me
- [ ] slowing me down but I'm able to continue working
- [ ] annoying
- [x] this feature was working in a previous version but is broken in the current release.

### Bruno version

2.2.0

### Operating System

Manjaro

### Describe the bug

Certain requests make the app crash

I'm not sure how to reproduce it, but it occurs from time to time, even on a fresh collection with ~3 requests.

Pretty sure it's something that began with a recent update though.

```
index.72ed0700.js:681 Object
static/diff2html.min.css:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
lib-react.41929aa2.js:2 TypeError: Cannot read properties of undefined (reading 'toLocaleString')
    at yI (index.72ed0700.js:7:291893)
    at lb (lib-react.41929aa2.js:2:41685)
    at aY (lib-react.41929aa2.js:2:61437)
    at ot (lib-react.41929aa2.js:2:72858)
    at ua (lib-react.41929aa2.js:2:111999)
    at lib-react.41929aa2.js:2:111844
    at ul (lib-react.41929aa2.js:2:111852)
    at i3 (lib-react.41929aa2.js:2:109022)
    at uT (lib-react.41929aa2.js:2:128880)
    at MessagePort.z (lib-react.41929aa2.js:2:180013)
aR @ lib-react.41929aa2.js:2
index.72ed0700.js:684 Objecterror: TypeError: Cannot read properties of undefined (reading 'toLocaleString')
    at yI (file:///snap/bruno/69/resources/app.asar/web/static/js/index.72ed0700.js:7:291893)
    at lb (file:///snap/bruno/69/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:41685)
    at aY (file:///snap/bruno/69/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:61437)
    at ot (file:///snap/bruno/69/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:72858)
    at ua (file:///snap/bruno/69/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:111999)
    at file:///snap/bruno/69/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:111844
    at ul (file:///snap/bruno/69/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:111852)
    at i3 (file:///snap/bruno/69/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:109022)
    at uT (file:///snap/bruno/69/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:128880)
    at MessagePort.z (file:///snap/bruno/69/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:180013)errorInfo: {componentStack: '\n    at yI (file:///snap/bruno/69/resources/app.as…pp.asar/web/static/js/index.72ed0700.js:684:31054'}[[Prototype]]: Object

```

### Screenshots/Live demo link

![Image](https://github.com/user-attachments/assets/19477a49-d76b-4bcb-8a01-a77a57e3acf1)

**Comment by Bradleykingz** [comment]
Return to app doesn't work either

![Image](https://github.com/user-attachments/assets/e407edb0-f4cd-447b-aba1-04312d72c76d)

**Comment by anusree-bruno** [comment]
@Bradleykingz 
Would you be able to share a sample collection to reproduce this?
Is this happening when you run a collection or while making a specific request?

**Comment by Bradleykingz** [comment]
I basically cannot make any request... It occurs even with a brand new collection. I've basically been unable to use Bruno since upgrading to v2.2.0

**Comment by Bradleykingz** [comment]
I've tracked down the error to this code (obfuscated):

```
(["font-size:0.75rem;font-weight:600;color:", ";"], t => t.theme.requestTabPanel.responseStatus)
              , yI = t => {
                let a, r;
                let n = (0,
                U.c)(3)
                  , {size: i} = t;
                a = i > 1024 ? Math.floor(i / 1024) + "." + Math.round(100 * (i % 1024 / 1024).toFixed(2)) + "KB" : i + "B";
                let o = i.toLocaleString() + "B"; // error occurs here
                return n[0] !== a || n[1] !== o ? (r = (0,
                H.jsx)(yF, {
                    title: o,
                    className: "ml-4",
                    children: a
                }),
                n[0] = a,
                n[1] = o,
                n[2] = r) : r = n[2],
                r
            }
```

Which corresponds to [this code](https://github.com/usebruno/bruno/blob/2ee7ce5829201f408db8bcfbe3cd2a2ddcb5127b/packages/bruno-app/src/components/ResponsePane/ResponseSize/index.js#L9)

```jsx
import React from 'react';
import StyledWrapper from './StyledWrapper';

const ResponseSize = ({ size }) => {
  let sizeToDisplay = '';

  if (size > 1024) {
    // size is greater than 1kb
    let kb = Math.floor(size / 1024);
    let decimal = Math.round(((size % 1024) / 1024).toFixed(2) * 100);
    sizeToDisplay = kb + '.' + decimal + 'KB';
  } else {
    sizeToDisplay = size + 'B';
  }

  return (
    <StyledWrapper title={size.toLocaleString() + 'B'} className="ml-4"> // here
      {sizeToDisplay}
    </StyledWrapper>
  );
};
export default ResponseSize;
```

I've made a request and created breakpoints around the calling code, and here is the response:

```
{
    "state": "success",
    "statusText": "ETIMEDOUT",
}
```

Fields like `data`, `headers`, `size` and `status` are undefined.

In this case, `i.toLocaleString()` would definitely lead to the error I'm seeing. I'd imagine the actual error in my case (this timeout was probably because of the breakpoints) is being hidden by this error.

**Comment by anusree-bruno** [comment]
Thanks @Bradleykingz for this. This is very helpful. I will check with the team on conditionally chaining this.

**Comment by AmAzing129** [comment]
> I basically cannot make any request... It occurs even with a brand new collection. I've basically been unable to use Bruno since upgrading to v2.2.0

I've basically been unable to use Bruno since upgrading to v2.2.0, too. Maybe a new release?

**Comment by preekmr** [comment]
> [@AmAzing129](https://github.com/AmAzing129) We have a release planned to go out coming Tuesday (13 May). Meanwhile if you're on Mac / Linux - you can checkout the latest nightly build at https://github.com/usebruno/bruno-nightly-builds which has the fixes

This is helpful. Thanks!
