### ISSUE TITLE
External NPM modules seem to be broken

### ISSUE THREAD

**Issue by nudasilva** [usebruno/bruno#7295]
### I have checked the following:

- [x] I have searched existing issues and found nothing related to my issue.

### This bug is:

- [x] making Bruno unusable for me
- [ ] slowing me down but I'm able to continue working
- [ ] annoying
- [ ] this feature was working in a previous version but is broken in the current release.

### Bruno version

3.1.4

### Operating System

Windows 11 - version 23H2

### Describe the bug

External NPM modules seem to be broken
Ex: When using const { readFileSync } = require('fs'), I have the following error:
Pre-Request Script Error
Error: Cannot find module totp-generator

moduleWhitelist is ignored (when adding fs)

It worked with Bruno 3.1.1

### Screenshots/Live demo link

<img width="1056" height="195" alt="Image" src="https://github.com/user-attachments/assets/10142355-cf9e-4e45-b635-1c2f7d89447e" />

**Comment by sanjaikumar-bruno** [comment]
@nudasilva 

Are you using developer mode? [Docs](https://docs.usebruno.com/configure/javascript-sandbox).

**Comment by sanjaikumar-bruno** [comment]
Hey @nudasilva, are you still facing this issue?

**Comment by nudasilva** [comment]
Yes, I still facing it in version 3.1.4, whereas 3.1.1 works fine.
