### ISSUE TITLE
`moduleWhitelist` Configuration Not Working for npm Packages in Bruno 3.0 CLI

### ISSUE THREAD

**Issue by lf-luliu** [usebruno/bruno#6683]
### I have checked the following:

- [x] I have searched existing issues and found nothing related to my issue.

### This bug is:

- [ ] making Bruno unusable for me
- [ ] slowing me down but I'm able to continue working
- [ ] annoying
- [x] this feature was working in a previous version but is broken in the current release.

### Bruno version

3.0.0

### Operating System

macOS 14.5 (23F79)

## Environment
- **Bruno CLI Version**: 3.0.0
- **Node.js Version**: v25.1.0
- **npm Version**: v11.6.2
- **OS**: macOS 14.5 (23F79)

## Problem Description

We are using external library in our tests, which work well in version 2.15.1, but it failed in version 3.0.0.

with the following error message:

```log
quick-js:execution-end:with-error Cannot find module lodash
Error executing the script! F [Error]: Cannot find module lodash
```

By reading the document, we added `filesystemAccess`, `moduleWhitelist`, `flow` to `bruno.json`, try to solve the module load issue, but it does not work.

## Additional Notes

- The same issue occurs in both Bruno CLI and Bruno GUI (version 3.0)
- This worked in previous versions of Bruno (before 3.0)
- The documentation suggests that `moduleWhitelist` should work for external npm packages, but the implementation appears incomplete

### `bruno.json`

```json
{
  "version": "1",
  "name": "external_lib_load_issue",
  "type": "collection",
  "ignore": [
    "node_modules",
    ".git"
  ],
  "scripts": {
    "filesystemAccess": {
      "allow": true
    },
    "moduleWhitelist": [
      "lodash"
    ]
  },
  "flow": "sequential"
}
```

### `package.json`
```json
{
  "name": "external_lib_load_issue"
  "version": "1.0.0",
  "description": "Reproduce issue",
  "dependencies": {
    "lodash": "^4.17.21"
  }
}
```

### Script Usage
In `collection.bru`

```javascript
script:pre-request {
  const _ = require("lodash");
  const data = _.partition([1, 2, 3, 4], n => n % 2);
  console.log("data", data);
}
```

## Steps to Reproduce

1. Create a Bruno collection with `bruno.json` containing `moduleWhitelist` configuration
2. Install npm dependencies: `npm install lodash`
3. Create a script that requires these modules: `const _ = require("lodash");`
4. Run the collection using Bruno CLI: `bru run`
5. Observe the error

## Expected Behavior

According to the Bruno documentation, after configuring `moduleWhitelist` and installing npm packages, scripts should be able to `require()` whitelisted modules successfully.

## Actual Behavior

The script fails with the following error:
```
Error executing the script! F [Error]: Cannot find module lodash
    at <anonymous> (eval.js:62)
Host: QuickJSUnwrapError
    at P.unwrapResult (~/.nvm/versions/node/v25.1.0/lib/node_modules/@usebruno/cli/node_modules/quickjs-emscripten-core/dist/index.js:4:13882)
    at executeQuickJsVmAsync (~/.nvm/versions/node/v25.1.0/lib/node_modules/@usebruno/cli/node_modules/@usebruno/js/src/sandbox/quickjs/index.js:182:31)
    at async ScriptRuntime.runRequestScript (~/.nvm/versions/node/v25.1.0/lib/node_modules/@usebruno/cli/node_modules/@usebruno/js/src/runtime/script-runtime.js:101:5)
    at async runSingleRequest (~/.nvm/versions/node/v25.1.0/lib/node_modules/@usebruno/cli/src/runner/run-single-request.js:174:22)
    at async runIteration (~/.nvm/versions/node/v25.1.0/lib/node_modules/@usebruno/cli/src/commands/run.js:995:24)
    at async Object.handler (~/.nvm/versions/node/v25.1.0/lib/node_modules/@usebruno/cli/src/commands/run.js:1151:33) {
  cause: {
    name: 'Error',
    message: 'Cannot find module lodash',
    stack: '    at <anonymous> (eval.js:62)\n'
  },
```

## Workaround

Currently, only pre-bundled libraries work. The `crypto-js` library is pre-bundled but still fails, suggesting there may be additional issues with the bundling or module resolution.

### 1. `moduleWhitelist` Configuration Not Passed to QuickJS Runtime

In `/node_modules/@usebruno/js/src/sandbox/quickjs/index.js`, the `executeQuickJsVmAsync` function (line 92) only receives `{ script, context, collectionPath }` parameters:

```javascript
const executeQuickJsVmAsync = async ({ script: externalScript, context: externalContext, collectionPath }) => {
  // ...
}
```

The `scriptingConfig` parameter (which contains `moduleWhitelist`) is **not passed** to this function, making it impossible for the QuickJS runtime to access the whitelist configuration.

### 2. Module Resolution Logic Doesn't Support Dynamic npm Module Loading

The `require` function implementation (lines 108-136) only supports:
- Pre-bundled libraries from `globalThis.requireObject`
- Local file modules (via `__brunoLoadLocalModule`)
- **No support for dynamic npm module resolution from `node_modules`**

```javascript
globalThis.require = (mod) => {
  let lib = globalThis.requireObject[mod];
  if (lib) {
    return lib;
  }
  else if (isModuleAPath(mod)) {
    // Load local module file
    let localModuleCode = globalThis.__brunoLoadLocalModule(mod);
    // ...
  }
  else {
    throw new Error("Cannot find module " + mod);  // ← Fails here for npm packages
  }
}
```

### 3. Only Pre-bundled Libraries Are Available

In `/node_modules/@usebruno/js/src/sandbox/bundle-libraries.js`, only specific libraries are pre-bundled:
- `chai`
- `moment`
- `buffer`
- `btoa`/`atob`
- `crypto-js` (pre-bundled, but still fails)
- `tv4`

Other npm packages like `lodash` and `jsrsasign` are not pre-bundled and cannot be loaded dynamically.

### Screenshots/Live demo link

<img width="760" height="101" alt="Image" src="https://github.com/user-attachments/assets/d6036442-7ad8-4950-b7e9-610b1df92d27" />

<img width="1512" height="303" alt="Image" src="https://github.com/user-attachments/assets/b7e8333a-8d3d-4bb6-bd72-8a37fbec4581" />

[external_lib_load_issue.zip](https://github.com/user-attachments/files/24444029/external_lib_load_issue.zip)

**Comment by sreelakshmi-bruno** [comment]
Hi @lf-luliu, thanks for reporting this. Apologies for the confusion. You need to be in `Developer mode` to use external libraries in GUI and CLI. In CLI, we have changed the default runtime to `Safe mode` in v3.0.0 so you'd need to pass in an extra flag `--sandbox=developer` to specify developer mode. The documentation for this has been likely missed. I will update it soon. Let me know if this solves the issue for you. Thanks!

**Comment by lf-luliu** [comment]
Hi @sreelakshmi-bruno thanks, it works when adding the flag. 
And also I noticed this in cli commands, but in the document it says developer mode is the default, so I did not add it. Please update [the document](https://docs.usebruno.com/bru-cli/commandOptions#setup-options).

<img width="846" height="89" alt="Image" src="https://github.com/user-attachments/assets/ef34f2b6-eebf-452b-9a1c-2554ba131629" />

**Comment by sreelakshmi-bruno** [comment]
We have updated the documentation. Thanks!

**Comment by andiabrudan** [comment]
Sorry to hijack this thread, but it's the exact problem that I have.

## How do you enter `Developer Mode` in GUI?

The flag is CLI only.  
V3 removed any options to do that in the settings menu.  (Nothing in the `Beta` menu, and no more `Security` menu)
No blog post, github issue, or developer documentation mentions anything about GUI dev mode.  
They all stop at the CLI `--sandbox` flag comment.  

This [blog post](https://blog.usebruno.com/bruno-v2-v3-breaking-changes) clearly states that

| Mode | v3 Runtime |
| --- | --- |
| Safe Mode | QuickJS (unchanged) |
| Developer Mode | NodeVM |

The error I'm getting is  
`quick-js:execution-end:with-error Cannot find module crypto `  
(It's every module that gives this error, not just crypto)
That means I'm in safe mode using the  GUI.

So how do I turn developer mode on?
